### ISSUE TITLE
ValueError with multidimensional parameter distribution

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGMLabSpain/InferPy#20]
Problem when defining a parameter which is a multidimensional distribution:

```
theta = inf.models.Normal(loc=[0., 0.], scale=1.)
x = inf.models.Normal(loc=theta, scale=1., observed=True)
```

raises the error below:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/inferpy/models/normal.py", line 90, in __init__
    loc_rep = self.__reshape_param(loc, self_shape)
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/inferpy/models/normal.py", line 165, in __reshape_param
    param_tf_mat = tf.reshape(tf.stack(param_vect), (D,))
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/env2.7/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3997, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/env2.7/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/env2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/env2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3208, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/env2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/env2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/env2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/env2.7/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/env2.7/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Cannot reshape a tensor with 2 elements to shape [1] (1 elements) for 'Reshape_25' (op: 'Reshape') with input shapes: [1,2], [1] and with input tensors computed as partial shapes: input[1] = [1].
```

**Comment by rcabanasdepaz** [comment]
solved: for computing the dimension of the new variable, the dimension of input parameters are taken into account:

```
theta = inf.models.Normal(loc=[0., 0.], scale=1.)
x = inf.models.Normal(loc=theta, scale=1., observed=True)

>>> x.shape

[2]


theta1 = inf.models.Normal(loc=0., scale=1.)
theta2 = inf.models.Normal(loc=0., scale=1.)

x = inf.models.Normal(loc=[theta1, theta2], scale=1., observed=True)

>>> x.shape

[2]

```
